[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/session"
  to = "/.netlify/functions/session"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from = "/api/enrich-spotify-artist"
  to = "/.netlify/functions/enrich-spotify-artist"
  status = 200

[[redirects]]
  from = "/netlify/*"
  to = "/index.html"
  status = 302
  force = true
